[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pytex"
version = "0.1"
authors = [
    { name="Junling Ma", email="junlingm@gmail.com" },
]
description = "A TeX parser in Python 3"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fonttools>=4.60.2",
    "pypdf>=6.9.1",
    "reportlab>=4.4.10",
    "pytest>=8.3.4",
    "uharfbuzz>=0.51.7",
]
