[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pytex"
version = "0.2"
authors = [
    { name="Junling Ma", email="junlingm@gmail.com" },
]
description = "A TeX parser in Python 3"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "afdko>=4.0.3",
    "fonttools>=4.60.2",
    "pillow>=11.3.0",
    "pypdf>=6.9.1",
    "python-docx>=1.2.0",
    "reportlab>=4.4.10",
    "drawsvg",
    "lxml",
    "pytest>=8.3.4",
    "uharfbuzz>=0.51.7",
    "pymupdf>=1.26.5"
]

[tool.setuptools.packages.find]
include = ["pytex", "pytex.*"]
