[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pytex"
version = "0.2.2"
authors = [
    { name="Junling Ma", email="junlingm@gmail.com" },
]
description = "A TeX parser in Python 3"
readme = "README.md"
license = "GPL-3.0-only"
license-files = ["LICENCE", "THIRD_PARTY_NOTICES.md"]
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Text Processing :: Markup :: LaTeX",
]
dependencies = [
    "afdko>=4.0.3",
    "fonttools>=4.60.2",
    "pillow>=11.3.0",
    "pypdf>=6.9.1",
    "python-docx>=1.2.0",
    "reportlab>=4.4.10",
    "drawsvg",
    "lxml",
    "uharfbuzz>=0.51.7",
    "pymupdf>=1.26.5"
]

[project.optional-dependencies]
test = ["pytest>=8.3.4"]

[project.urls]
Documentation = "https://github.com/roverrobot/pytex#readme"
Repository = "https://github.com/roverrobot/pytex"
Issues = "https://github.com/roverrobot/pytex/issues"

[tool.setuptools.packages.find]
include = ["pytex", "pytex.*"]

[tool.setuptools.package-data]
pytex = ["data/formats/*.pfmt"]
